program TransactionMaster;

uses
  Vcl.Forms,
  Ntapi.ntdbg in 'NtUtils\Headers\Ntapi.ntdbg.pas',
  Ntapi.ntdef in 'NtUtils\Headers\Ntapi.ntdef.pas',
  Ntapi.ntexapi in 'NtUtils\Headers\Ntapi.ntexapi.pas',
  Ntapi.ntioapi in 'NtUtils\Headers\Ntapi.ntioapi.pas',
  Ntapi.ntkeapi in 'NtUtils\Headers\Ntapi.ntkeapi.pas',
  Ntapi.ntldr in 'NtUtils\Headers\Ntapi.ntldr.pas',
  Ntapi.ntlpcapi in 'NtUtils\Headers\Ntapi.ntlpcapi.pas',
  Ntapi.ntmmapi in 'NtUtils\Headers\Ntapi.ntmmapi.pas',
  Ntapi.ntobapi in 'NtUtils\Headers\Ntapi.ntobapi.pas',
  Ntapi.ntpebteb in 'NtUtils\Headers\Ntapi.ntpebteb.pas',
  Ntapi.ntpsapi in 'NtUtils\Headers\Ntapi.ntpsapi.pas',
  Ntapi.ntregapi in 'NtUtils\Headers\Ntapi.ntregapi.pas',
  Ntapi.ntrtl in 'NtUtils\Headers\Ntapi.ntrtl.pas',
  Ntapi.ntsam in 'NtUtils\Headers\Ntapi.ntsam.pas',
  Ntapi.ntseapi in 'NtUtils\Headers\Ntapi.ntseapi.pas',
  Ntapi.ntstatus in 'NtUtils\Headers\Ntapi.ntstatus.pas',
  Ntapi.nttmapi in 'NtUtils\Headers\Ntapi.nttmapi.pas',
  Ntapi.ntwow64 in 'NtUtils\Headers\Ntapi.ntwow64.pas',
  Winapi.ConsoleApi in 'NtUtils\Headers\Winapi.ConsoleApi.pas',
  Winapi.ntlsa in 'NtUtils\Headers\Winapi.ntlsa.pas',
  Winapi.NtSecApi in 'NtUtils\Headers\Winapi.NtSecApi.pas',
  Winapi.ProcessThreadsApi in 'NtUtils\Headers\Winapi.ProcessThreadsApi.pas',
  Winapi.Sddl in 'NtUtils\Headers\Winapi.Sddl.pas',
  Winapi.securitybaseapi in 'NtUtils\Headers\Winapi.securitybaseapi.pas',
  Winapi.Shell in 'NtUtils\Headers\Winapi.Shell.pas',
  Winapi.Shlwapi in 'NtUtils\Headers\Winapi.Shlwapi.pas',
  Winapi.Svc in 'NtUtils\Headers\Winapi.Svc.pas',
  Winapi.UserEnv in 'NtUtils\Headers\Winapi.UserEnv.pas',
  Winapi.Wdc in 'NtUtils\Headers\Winapi.Wdc.pas',
  Winapi.WinBase in 'NtUtils\Headers\Winapi.WinBase.pas',
  Winapi.WinError in 'NtUtils\Headers\Winapi.WinError.pas',
  Winapi.WinNt in 'NtUtils\Headers\Winapi.WinNt.pas',
  Winapi.WinSafer in 'NtUtils\Headers\Winapi.WinSafer.pas',
  Winapi.winsta in 'NtUtils\Headers\Winapi.winsta.pas',
  Winapi.WinUser in 'NtUtils\Headers\Winapi.WinUser.pas',
  DelphiUtils.Arrays in 'NtUtils\DelphiUtils.Arrays.pas',
  DelphiUtils.Events in 'NtUtils\DelphiUtils.Events.pas',
  DelphiUtils.Strings in 'NtUtils\DelphiUtils.Strings.pas',
  NtUtils.Access.Expected in 'NtUtils\NtUtils.Access.Expected.pas',
  NtUtils.Access in 'NtUtils\NtUtils.Access.pas',
  NtUtils.AutoHandle in 'NtUtils\NtUtils.AutoHandle.pas',
  NtUtils.Debug.HardwareBP in 'NtUtils\NtUtils.Debug.HardwareBP.pas',
  NtUtils.Debug in 'NtUtils\NtUtils.Debug.pas',
  NtUtils.Environment in 'NtUtils\NtUtils.Environment.pas',
  NtUtils.ErrorMsg in 'NtUtils\NtUtils.ErrorMsg.pas',
  NtUtils.Exceptions in 'NtUtils\NtUtils.Exceptions.pas',
  NtUtils.Exceptions.Report in 'NtUtils\NtUtils.Exceptions.Report.pas',
  NtUtils.Exec.Nt in 'NtUtils\NtUtils.Exec.Nt.pas',
  NtUtils.Exec in 'NtUtils\NtUtils.Exec.pas',
  NtUtils.Exec.Shell in 'NtUtils\NtUtils.Exec.Shell.pas',
  NtUtils.Exec.Wdc in 'NtUtils\NtUtils.Exec.Wdc.pas',
  NtUtils.Exec.Win32 in 'NtUtils\NtUtils.Exec.Win32.pas',
  NtUtils.Exec.Wmi in 'NtUtils\NtUtils.Exec.Wmi.pas',
  NtUtils.Files in 'NtUtils\NtUtils.Files.pas',
  NtUtils.Job in 'NtUtils\NtUtils.Job.pas',
  NtUtils.Ldr in 'NtUtils\NtUtils.Ldr.pas',
  NtUtils.Lsa.Audit in 'NtUtils\NtUtils.Lsa.Audit.pas',
  NtUtils.Lsa.Logon in 'NtUtils\NtUtils.Lsa.Logon.pas',
  NtUtils.Lsa in 'NtUtils\NtUtils.Lsa.pas',
  NtUtils.Lsa.Security in 'NtUtils\NtUtils.Lsa.Security.pas',
  NtUtils.Lsa.Sid in 'NtUtils\NtUtils.Lsa.Sid.pas',
  NtUtils.Objects.Compare in 'NtUtils\NtUtils.Objects.Compare.pas',
  NtUtils.Objects.Namespace in 'NtUtils\NtUtils.Objects.Namespace.pas',
  NtUtils.Objects in 'NtUtils\NtUtils.Objects.pas',
  NtUtils.Objects.Security in 'NtUtils\NtUtils.Objects.Security.pas',
  NtUtils.Objects.Snapshots in 'NtUtils\NtUtils.Objects.Snapshots.pas',
  NtUtils.Processes.Memory in 'NtUtils\NtUtils.Processes.Memory.pas',
  NtUtils.Processes in 'NtUtils\NtUtils.Processes.pas',
  NtUtils.Processes.Snapshots in 'NtUtils\NtUtils.Processes.Snapshots.pas',
  NtUtils.Profiles in 'NtUtils\NtUtils.Profiles.pas',
  NtUtils.Registry.HKCU in 'NtUtils\NtUtils.Registry.HKCU.pas',
  NtUtils.Registry in 'NtUtils\NtUtils.Registry.pas',
  NtUtils.Sam in 'NtUtils\NtUtils.Sam.pas',
  NtUtils.Sam.Security in 'NtUtils\NtUtils.Sam.Security.pas',
  NtUtils.Sections in 'NtUtils\NtUtils.Sections.pas',
  NtUtils.Security.Acl in 'NtUtils\NtUtils.Security.Acl.pas',
  NtUtils.Security.AppContainer in 'NtUtils\NtUtils.Security.AppContainer.pas',
  NtUtils.Security.Sid in 'NtUtils\NtUtils.Security.Sid.pas',
  NtUtils.Shellcode in 'NtUtils\NtUtils.Shellcode.pas',
  NtUtils.Strings in 'NtUtils\NtUtils.Strings.pas',
  NtUtils.Svc in 'NtUtils\NtUtils.Svc.pas',
  NtUtils.Svc.Security in 'NtUtils\NtUtils.Svc.Security.pas',
  NtUtils.Svc.SingleTaskSvc in 'NtUtils\NtUtils.Svc.SingleTaskSvc.pas',
  NtUtils.Threads in 'NtUtils\NtUtils.Threads.pas',
  NtUtils.Threads.Stack in 'NtUtils\NtUtils.Threads.Stack.pas',
  NtUtils.Tokens.Impersonate in 'NtUtils\NtUtils.Tokens.Impersonate.pas',
  NtUtils.Tokens.Logon in 'NtUtils\NtUtils.Tokens.Logon.pas',
  NtUtils.Tokens.Misc in 'NtUtils\NtUtils.Tokens.Misc.pas',
  NtUtils.Tokens in 'NtUtils\NtUtils.Tokens.pas',
  NtUtils.Tokens.Query in 'NtUtils\NtUtils.Tokens.Query.pas',
  NtUtils.Transactions in 'NtUtils\NtUtils.Transactions.pas',
  NtUtils.Transactions.Remote in 'NtUtils\NtUtils.Transactions.Remote.pas',
  NtUtils.WinSafer in 'NtUtils\NtUtils.WinSafer.pas',
  NtUtils.WinStation in 'NtUtils\NtUtils.WinStation.pas',
  NtUtils.WinUser in 'NtUtils\NtUtils.WinUser.pas',
  NtUtils.WinUser.WinstaLock in 'NtUtils\NtUtils.WinUser.WinstaLock.pas',
  NtUiLib.Exceptions in 'NtUtils\NtUiLib\NtUiLib.Exceptions.pas',
  NtUiLib.HysteresisList in 'NtUtils\NtUiLib\NtUiLib.HysteresisList.pas',
  NtUiLib.Icons in 'NtUtils\NtUiLib\NtUiLib.Icons.pas',
  VclEx.ListView in 'VclEx\VclEx.ListView.pas',
  MainForm in 'UI\MainForm.pas' {FormMain},
  TransactionInfo in 'UI\TransactionInfo.pas' {FormTmTxInfo},
  ProcessList in 'UI\ProcessList.pas' {FormProcessList},
  ProcessInfo in 'UI\ProcessInfo.pas' {FormProcessInfo};

{$R *.res}

begin
  {$IFDEF Debug} ReportMemoryLeaksOnShutdown := True; {$ENDIF}
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TFormMain, FormMain);
  Application.Run;
end.
