program TransactionMaster;

{$WEAKLINKRTTI ON}

uses
  Vcl.Forms,
  VclEx.ListView in 'NtUtilsUI\VclEx\VclEx.ListView.pas',
  MainForm in 'UI\MainForm.pas' {FormMain},
  TransactionInfo in 'UI\TransactionInfo.pas' {FormTmTxInfo},
  ProcessList in 'UI\ProcessList.pas' {FormProcessList},
  ProcessInfo in 'UI\ProcessInfo.pas' {FormProcessInfo},
  TmTxTrackerUtils in 'TmTxTrackerUtils.pas',
  ProcessTransact in 'UI\ProcessTransact.pas' {FormTransact},
  DelphiApi.Reflection in 'NtUtilsUI\NtUtils\Headers\DelphiApi.Reflection.pas',
  Ntapi.ntdbg in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntdbg.pas',
  Ntapi.ntdef in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntdef.pas',
  Ntapi.ntexapi in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntexapi.pas',
  Ntapi.ntioapi in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntioapi.pas',
  Ntapi.ntkeapi in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntkeapi.pas',
  Ntapi.ntldr in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntldr.pas',
  Ntapi.ntlpcapi in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntlpcapi.pas',
  Ntapi.ntmmapi in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntmmapi.pas',
  Ntapi.ntobapi in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntobapi.pas',
  Ntapi.ntpebteb in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntpebteb.pas',
  Ntapi.ntpsapi in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntpsapi.pas',
  Ntapi.ntregapi in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntregapi.pas',
  Ntapi.ntrtl in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntrtl.pas',
  Ntapi.ntsam in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntsam.pas',
  Ntapi.ntseapi in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntseapi.pas',
  Ntapi.ntstatus in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntstatus.pas',
  Ntapi.nttmapi in 'NtUtilsUI\NtUtils\Headers\Ntapi.nttmapi.pas',
  Ntapi.ntwow64 in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntwow64.pas',
  NtUtils.Version in 'NtUtilsUI\NtUtils\Headers\NtUtils.Version.pas',
  Winapi.ConsoleApi in 'NtUtilsUI\NtUtils\Headers\Winapi.ConsoleApi.pas',
  Winapi.ntlsa in 'NtUtilsUI\NtUtils\Headers\Winapi.ntlsa.pas',
  Winapi.NtSecApi in 'NtUtilsUI\NtUtils\Headers\Winapi.NtSecApi.pas',
  Winapi.ProcessThreadsApi in 'NtUtilsUI\NtUtils\Headers\Winapi.ProcessThreadsApi.pas',
  Winapi.Sddl in 'NtUtilsUI\NtUtils\Headers\Winapi.Sddl.pas',
  Winapi.securitybaseapi in 'NtUtilsUI\NtUtils\Headers\Winapi.securitybaseapi.pas',
  Winapi.Shell in 'NtUtilsUI\NtUtils\Headers\Winapi.Shell.pas',
  Winapi.Shlwapi in 'NtUtilsUI\NtUtils\Headers\Winapi.Shlwapi.pas',
  Winapi.Svc in 'NtUtilsUI\NtUtils\Headers\Winapi.Svc.pas',
  Winapi.UserEnv in 'NtUtilsUI\NtUtils\Headers\Winapi.UserEnv.pas',
  Winapi.WinBase in 'NtUtilsUI\NtUtils\Headers\Winapi.WinBase.pas',
  Winapi.WinError in 'NtUtilsUI\NtUtils\Headers\Winapi.WinError.pas',
  Winapi.WinNt in 'NtUtilsUI\NtUtils\Headers\Winapi.WinNt.pas',
  Winapi.WinSafer in 'NtUtilsUI\NtUtils\Headers\Winapi.WinSafer.pas',
  Winapi.winsta in 'NtUtilsUI\NtUtils\Headers\Winapi.winsta.pas',
  Winapi.WinUser in 'NtUtilsUI\NtUtils\Headers\Winapi.WinUser.pas',
  DelphiUtils.Arrays in 'NtUtilsUI\NtUtils\DelphiUtils.Arrays.pas',
  DelphiUtils.AutoObject in 'NtUtilsUI\NtUtils\DelphiUtils.AutoObject.pas',
  DelphiUtils.Events in 'NtUtilsUI\NtUtils\DelphiUtils.Events.pas',
  NtUtils.Access.Expected in 'NtUtilsUI\NtUtils\NtUtils.Access.Expected.pas',
  NtUtils.Environment in 'NtUtilsUI\NtUtils\NtUtils.Environment.pas',
  NtUtils.Exec in 'NtUtilsUI\NtUtils\NtUtils.Exec.pas',
  NtUtils.Exec.Win32 in 'NtUtilsUI\NtUtils\NtUtils.Exec.Win32.pas',
  NtUtils.Files in 'NtUtilsUI\NtUtils\NtUtils.Files.pas',
  NtUtils.ImageHlp in 'NtUtilsUI\NtUtils\NtUtils.ImageHlp.pas',
  NtUtils.Ldr in 'NtUtilsUI\NtUtils\NtUtils.Ldr.pas',
  NtUtils.Lsa in 'NtUtilsUI\NtUtils\NtUtils.Lsa.pas',
  NtUtils.Objects in 'NtUtilsUI\NtUtils\NtUtils.Objects.pas',
  NtUtils.Objects.Snapshots in 'NtUtilsUI\NtUtils\NtUtils.Objects.Snapshots.pas',
  NtUtils in 'NtUtilsUI\NtUtils\NtUtils.pas',
  NtUtils.Processes.Memory in 'NtUtilsUI\NtUtils\NtUtils.Processes.Memory.pas',
  NtUtils.Processes.Modules in 'NtUtilsUI\NtUtils\NtUtils.Processes.Modules.pas',
  NtUtils.Processes in 'NtUtilsUI\NtUtils\NtUtils.Processes.pas',
  NtUtils.Processes.Query in 'NtUtilsUI\NtUtils\NtUtils.Processes.Query.pas',
  NtUtils.Processes.Snapshots in 'NtUtilsUI\NtUtils\NtUtils.Processes.Snapshots.pas',
  NtUtils.Sections in 'NtUtilsUI\NtUtils\NtUtils.Sections.pas',
  NtUtils.Security.Acl in 'NtUtilsUI\NtUtils\NtUtils.Security.Acl.pas',
  NtUtils.Security.Sid in 'NtUtilsUI\NtUtils\NtUtils.Security.Sid.pas',
  NtUtils.Shellcode.Dll in 'NtUtilsUI\NtUtils\NtUtils.Shellcode.Dll.pas',
  NtUtils.Shellcode in 'NtUtilsUI\NtUtils\NtUtils.Shellcode.pas',
  NtUtils.System in 'NtUtilsUI\NtUtils\NtUtils.System.pas',
  NtUtils.SysUtils in 'NtUtilsUI\NtUtils\NtUtils.SysUtils.pas',
  NtUtils.Threads in 'NtUtilsUI\NtUtils\NtUtils.Threads.pas',
  NtUtils.Tokens.Impersonate in 'NtUtilsUI\NtUtils\NtUtils.Tokens.Impersonate.pas',
  NtUtils.Tokens.Misc in 'NtUtilsUI\NtUtils\NtUtils.Tokens.Misc.pas',
  NtUtils.Tokens in 'NtUtilsUI\NtUtils\NtUtils.Tokens.pas',
  NtUtils.Tokens.Query in 'NtUtilsUI\NtUtils\NtUtils.Tokens.Query.pas',
  NtUtils.Transactions in 'NtUtilsUI\NtUtils\NtUtils.Transactions.pas',
  NtUtils.Transactions.Remote in 'NtUtilsUI\NtUtils\NtUtils.Transactions.Remote.pas',
  NtUtils.WinStation in 'NtUtilsUI\NtUtils\NtUtils.WinStation.pas',
  NtUtils.WinUser in 'NtUtilsUI\NtUtils\NtUtils.WinUser.pas',
  DelphiUiLib.HysteresisList in 'NtUtilsUI\NtUtils\NtUiLib\DelphiUiLib.HysteresisList.pas',
  DelphiUiLib.Strings in 'NtUtilsUI\NtUtils\NtUiLib\DelphiUiLib.Strings.pas',
  NtUiLib.AccessMasks in 'NtUtilsUI\NtUtils\NtUiLib\NtUiLib.AccessMasks.pas',
  NtUiLib.Exceptions.Dialog in 'NtUtilsUI\NtUtils\NtUiLib\NtUiLib.Exceptions.Dialog.pas',
  NtUiLib.Exceptions.Messages in 'NtUtilsUI\NtUtils\NtUiLib\NtUiLib.Exceptions.Messages.pas',
  NtUiLib.Exceptions in 'NtUtilsUI\NtUtils\NtUiLib\NtUiLib.Exceptions.pas',
  NtUiLib.Exceptions.Report in 'NtUtilsUI\NtUtils\NtUiLib\NtUiLib.Exceptions.Report.pas',
  DelphiUiLib.Reflection.Numeric in 'NtUtilsUI\NtUtils\NtUiLib\DelphiUiLib.Reflection.Numeric.pas',
  NtUtils.Processes.Create.Win32 in 'NtUtilsUI\NtUtils\NtUtils.Processes.Create.Win32.pas',
  UI.ProcessIcons in 'NtUtilsUI\Common\UI.ProcessIcons.pas',
  VclEx.Form in 'NtUtilsUI\VclEx\VclEx.Form.pas';

{$R *.res}

begin
  {$IFDEF Debug} ReportMemoryLeaksOnShutdown := True; {$ENDIF}
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.HintHidePause := 25000;
  Application.CreateForm(TFormMain, FormMain);
  Application.Run;
end.
